DROP DATABASE AVALIACAO;

CREATE SCHEMA AVALIACAO;

USE AVALIACAO;

-- CREATE USER 'user'@'localhost' IDENTIFIED BY 'pass123';

GRANT SELECT, INSERT, DELETE, UPDATE ON AVALIACAO.* TO user@'localhost';

CREATE TABLE USUARIO (
    USU_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL,
    USU_CPF_CNPJ VARCHAR(100) NOT NULL,
    CONSTRAINT USU_NOME_USUARIO_UK UNIQUE (USU_CPF_CNPJ)
);

CREATE TABLE FUNCIONARIO (
    FUNC_ID BIGINT UNSIGNED PRIMARY KEY,
    FUNC_CARGO VARCHAR(100) NOT NULL,
    FUNC_SALARIO FLOAT,
    CONSTRAINT FUNC_USU_FK FOREIGN KEY (FUNC_ID)
    REFERENCES USUARIO (USU_ID)
);

CREATE TABLE CLIENTE (
    CLI_ID BIGINT UNSIGNED PRIMARY KEY,
    CONSTRAINT CLI_USU_FK FOREIGN KEY (CLI_ID)
    REFERENCES USUARIO (USU_ID)
);

CREATE TABLE CARTAO (
    CLI_ID BIGINT UNSIGNED,
    CAR_NUMERO VARCHAR(20) PRIMARY KEY,
    CAR_NOME VARCHAR(100) NOT NULL,
    CAR_DATA VARCHAR(5) NOT NULL,
    CAR_COD_SEGURANCA VARCHAR(3) NOT NULL,
    FOREIGN KEY (CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE PRODUTO (
    PROD_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    PROD_NOME VARCHAR(40) NOT NULL,
    PROD_MARCA VARCHAR(40) NOT NULL,
    PROD_UN_MEDIDA VARCHAR(20) NOT NULL,
    PROD_PRECO INT
);

CREATE TABLE VENDA (
    VENDA_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    VALOR_TOTAL_VENDA FLOAT NOT NULL,
    FORMA_PGTO_VENDA VARCHAR(20) NOT NULL,
    CLI_ID BIGINT UNSIGNED NOT NULL,
    PROD_ID BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUTO(PROD_ID),
    FOREIGN KEY (CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE PRODUTO_VENDA (
    PROD_ID BIGINT UNSIGNED NOT NULL,
    VENDA_ID BIGINT UNSIGNED NOT NULL,
    QUANTIDADE_PROD INT NOT NULL,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUTO(PROD_ID),
    FOREIGN KEY (VENDA_ID) REFERENCES VENDA(VENDA_ID)
);

CREATE TABLE ENDERECO (
    END_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    END_LOGRADOURO VARCHAR(100) NOT NULL,
    END_NUMERO VARCHAR(50) NOT NULL,
    END_BAIRRO VARCHAR(30) NOT NULL,
    END_CEP VARCHAR(9) NOT NULL,
    END_CIDADE VARCHAR(30) NOT NULL,
    END_CMPL VARCHAR(40) NOT NULL
);

CREATE TABLE FORNECEDOR (
    FORN_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    FORN_NOME VARCHAR(100) NOT NULL,
    FORN_CATEGORIA VARCHAR(40) NOT NULL,
    ENDERECO_ID BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(END_ID)
);

CREATE TABLE PRODUTO_FORNECEDOR (
    PROD_ID BIGINT UNSIGNED UNIQUE,
    FORN_ID BIGINT UNSIGNED UNIQUE,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUTO(PROD_ID),
    FOREIGN KEY (FORN_ID) REFERENCES FORNECEDOR(FORN_ID)
);